export const products = [
  {
    id: "1",
    title: "Handwoven Dhaka Malmal Saree",
    price: 260,
    originalPrice: 300,
    rating: 4.5,
    reviews: 150,
    description:
      "Elegant handwoven saree made with Dhaka and Malmal cotton, lightweight yet luxurious for all-day wear.",
    images: [
      "/products/malmal-sirak.png",
      "/products/malmal-ruffle.png",
      "/products/malmal-frok.png",
      "/products/malmal-bhoto.png",
    ],
    colors: [
      { name: "Maroon", value: "#800000" },
      { name: "Royal Blue", value: "#4169E1" },
      { name: "Olive Green", value: "#556B2F" },
    ],
    sizes: ["Free Size"],
  },
  {
    id: "2",
    title: "Dhaka Malmal Kurta Set",
    price: 260,
    originalPrice: 300,
    rating: 4.7,
    reviews: 95,
    description:
      "Traditional Dhaka Malmal cotton kurta set designed for both elegance and comfort.",
    images: [
      "/products/malmal-sirak.png",
      "/products/malmal-ruffle.png",
      "/products/malmal-frok.png",
      "/products/malmal-bhoto.png",
    ],
    colors: [
      { name: "White", value: "#FFFFFF" },
      { name: "Black", value: "#000000" },
      { name: "Gray", value: "#808080" },
    ],
    sizes: ["Small", "Medium", "Large", "X-Large"],
  },
  {
    id: "3",
    title: "Malmal Cotton Frock",
    price: 220,
    originalPrice: 280,
    rating: 4.6,
    reviews: 120,
    description:
      "Soft and breathable Malmal frock, handcrafted with delicate Dhaka patterns for a stylish look.",
    images: [
      "/products/malmal-sirak.png",
      "/products/malmal-ruffle.png",
      "/products/malmal-frok.png",
      "/products/malmal-bhoto.png",
    ],
    colors: [
      { name: "Pink", value: "#FFC0CB" },
      { name: "Sky Blue", value: "#87CEEB" },
      { name: "Lemon Yellow", value: "#FFF44F" },
    ],
    sizes: ["Small", "Medium", "Large", "X-Large"],
  },
  {
    id: "4",
    title: "Dhaka Malmal Shawl",
    price: 320,
    originalPrice: 400,
    rating: 4.8,
    reviews: 180,
    description:
      "Luxurious Dhaka Malmal shawl, handwoven with intricate patterns for warmth and grace.",
    images: [
      "/products/malmal-sirak.png",
      "/products/malmal-ruffle.png",
      "/products/malmal-frok.png",
      "/products/malmal-bhoto.png",
    ],
    colors: [
      { name: "Beige", value: "#F5F5DC" },
      { name: "Dark Red", value: "#8B0000" },
      { name: "Indigo", value: "#4B0082" },
    ],
    sizes: ["Free Size"],
  },
  {
    id: "5",
    title: "Dhaka Malmal Checkered Shirt",
    price: 300,
    originalPrice: 350,
    rating: 4.4,
    reviews: 90,
    description:
      "Stylish checkered shirt crafted from Dhaka Malmal fabric — breathable, soft, and durable.",
    images: [
      "/products/malmal-sirak.png",
      "/products/malmal-ruffle.png",
      "/products/malmal-frok.png",
      "/products/malmal-bhoto.png",
    ],
    colors: [
      { name: "Brown", value: "#A52A2A" },
      { name: "Gray", value: "#808080" },
      { name: "Green", value: "#228B22" },
    ],
    sizes: ["Small", "Medium", "Large", "X-Large"],
  },
  {
    id: "6",
    title: "Baby Malmal Cotton Bhoto Set",
    price: 250,
    originalPrice: 280,
    rating: 4.3,
    reviews: 110,
    description:
      "Hand-stitched baby Bhoto and Suruwal set made from gentle Malmal cotton, perfect for infants’ comfort.",
    images: [
      "/products/malmal-sirak.png",
      "/products/malmal-ruffle.png",
      "/products/malmal-frok.png",
      "/products/malmal-bhoto.png",
    ],
    colors: [
      { name: "White", value: "#FFFFFF" },
      { name: "Peach", value: "#FFDAB9" },
      { name: "Sky Blue", value: "#87CEEB" },
    ],
    sizes: ["0-6 Months", "6-12 Months", "1-2 Years"],
  },
  {
    id: "7",
    title: "Dhaka Malmal Striped Kurti",
    price: 270,
    originalPrice: 310,
    rating: 4.7,
    reviews: 140,
    description:
      "Modern striped kurti blending Dhaka designs with Malmal comfort, perfect for daily and festive wear.",
    images: [
      "/products/malmal-sirak.png",
      "/products/malmal-ruffle.png",
      "/products/malmal-frok.png",
      "/products/malmal-bhoto.png",
    ],
    colors: [
      { name: "Black & White", value: "#000000 & #FFFFFF" },
      { name: "Blue & White", value: "#0000FF & #FFFFFF" },
      { name: "Green & White", value: "#228B22 & #FFFFFF" },
    ],
    sizes: ["Small", "Medium", "Large", "X-Large"],
  },
  {
    id: "8",
    title: "Dhaka Graphic Print Shawl",
    price: 240,
    originalPrice: 280,
    rating: 4.6,
    reviews: 160,
    description: "Unique graphic print shawl made with soft Malmal cotton and Dhaka artistry.",
    images: [
      "/products/malmal-sirak.png",
      "/products/malmal-ruffle.png",
      "/products/malmal-frok.png",
      "/products/malmal-bhoto.png",
    ],
    colors: [
      { name: "Red", value: "#FF4500" },
      { name: "Gray", value: "#696969" },
      { name: "Navy", value: "#000080" },
    ],
    sizes: ["Free Size"],
  },
  {
    id: "9",
    title: "Dhaka Malmal Summer Shorts",
    price: 220,
    originalPrice: 270,
    rating: 4.2,
    reviews: 80,
    description:
      "Lightweight Malmal cotton shorts with Dhaka-inspired patterns, ideal for summer comfort.",
    images: [
      "/products/malmal-sirak.png",
      "/products/malmal-ruffle.png",
      "/products/malmal-frok.png",
      "/products/malmal-bhoto.png",
    ],
    colors: [
      { name: "Khaki", value: "#F0E68C" },
      { name: "Navy", value: "#000080" },
      { name: "Black", value: "#000000" },
    ],
    sizes: ["Small", "Medium", "Large", "X-Large"],
  },
  {
    id: "10",
    title: "3-Layer Dhaka Malmal Khasto Sirak",
    price: 330,
    originalPrice: 380,
    rating: 4.9,
    reviews: 200,
    description:
      "Premium 3-layer Khasto Sirak made of Malmal cotton and Dhaka weave for comfort and warmth.",
    images: [
      "/products/malmal-sirak.png",
      "/products/malmal-ruffle.png",
      "/products/malmal-frok.png",
      "/products/malmal-bhoto.png",
    ],
    colors: [
      { name: "Light Beige", value: "#F5F5DC" },
      { name: "Gray", value: "#808080" },
      { name: "Dark Blue", value: "#2C3E50" },
    ],
    sizes: ["Single", "Double", "Queen"],
  },
];
